### ISSUE TITLE
Will gomvn support https?

### ISSUE THREAD

**Issue by hollykbuck** [gomvn/gomvn#3]

**Comment by hollykbuck** [comment]
I have written an implementation in #4 , which introduced two optional key to Server config

the config file looks like this

```yaml
name: Maven Repository

server:
  host: 0.0.0.0
  port: 8080
  cert: server.crt # optional
  key: server.key # optional

repository:
  - release
  - snapshot
```

While `server.cert` is empty or missing, fiber will normally listen as http server. 

`server.crt` and `server.key` can be generated by openssl

```bash
 openssl req -newkey rsa:2048 -nodes -keyout server.key -x509 -days 365 -out server.crt -subj "/C=US/ST=CA/L=SanFrancisco/O=TestOrg/OU=IT/CN=gomvn.localtest.me"
```
